# Generated by Django 4.1.7 on 2023-04-12 05:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product_app', '0003_remove_product_discount_price_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='size',
            field=models.CharField(default=1, max_length=30),
            preserve_default=False,
        ),
    ]
