# Generated by Django 4.2 on 2023-04-13 05:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product_app', '0009_rename_image_cartitem_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartitem',
            name='Image',
            field=models.ImageField(upload_to=''),
        ),
    ]
