# Generated by Django 4.2 on 2023-04-13 05:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product_app', '0010_alter_cartitem_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cartitem',
            name='Image',
        ),
    ]
