# Generated by Django 4.1.7 on 2023-04-17 03:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product_app', '0011_remove_cartitem_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartitem',
            name='Image',
            field=models.ImageField(default=4, upload_to='products/images'),
            preserve_default=False,
        ),
    ]
