# Generated by Django 4.1.7 on 2023-04-17 04:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product_app', '0012_cartitem_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cartitem',
            name='Image',
        ),
        migrations.AddField(
            model_name='cartitem',
            name='image_url',
            field=models.ImageField(blank=True, null=True, upload_to='product/images'),
        ),
    ]
