# Generated by Django 4.1.7 on 2023-04-17 05:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product_app', '0014_alter_cartitem_image_url'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item', models.CharField(max_length=100)),
                ('image', models.ImageField(upload_to='product/images/')),
                ('price', models.FloatField(default=0)),
                ('size', models.CharField(max_length=20)),
                ('quantity', models.IntegerField(default=0)),
            ],
        ),
    ]
