# Generated by Django 4.1.7 on 2023-04-17 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product_app', '0017_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='rating_product',
            field=models.IntegerField(default=4),
            preserve_default=False,
        ),
    ]
