# Generated by Django 4.1.7 on 2023-04-17 09:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product_app', '0018_product_rating_product'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='rating_product',
        ),
        migrations.DeleteModel(
            name='Rating',
        ),
    ]
