# Generated by Django 4.2 on 2023-04-18 04:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product_app', '0020_rating'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='rating',
            options={'ordering': ['item']},
        ),
        migrations.RenameField(
            model_name='product',
            old_name='product_name',
            new_name='item',
        ),
        migrations.RenameField(
            model_name='rating',
            old_name='product',
            new_name='item',
        ),
    ]
