# Generated by Django 4.2 on 2023-04-25 08:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product_app', '0023_item_rating_product_rating_delete_rating_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Item_Rating',
        ),
    ]
