# Generated by Django 4.2 on 2023-04-25 08:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product_app', '0024_delete_item_rating'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='rating',
            new_name='item_rating',
        ),
    ]
