# Generated by Django 4.2 on 2023-04-25 08:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product_app', '0025_rename_rating_product_item_rating'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='item_rating',
            new_name='product_rating',
        ),
    ]
