# Generated by Django 4.2 on 2023-04-25 08:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product_app', '0026_rename_item_rating_product_product_rating'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='product_rating',
            new_name='rating',
        ),
        migrations.CreateModel(
            name='Item_Rating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('one', models.PositiveIntegerField(blank=True, default=0, null=True)),
                ('two', models.PositiveIntegerField(blank=True, default=0, null=True)),
                ('three', models.PositiveIntegerField(blank=True, default=0, null=True)),
                ('four', models.PositiveIntegerField(blank=True, default=0, null=True)),
                ('five', models.PositiveIntegerField(blank=True, default=0, null=True)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='itemrating', to='product_app.product')),
            ],
            options={
                'ordering': ['item'],
            },
        ),
    ]
