# Generated by Django 4.2 on 2023-04-25 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product_app', '0027_rename_product_rating_product_rating_item_rating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item_rating',
            name='five',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='item_rating',
            name='four',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='item_rating',
            name='one',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='item_rating',
            name='three',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='item_rating',
            name='two',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
