# Generated by Django 4.2 on 2023-05-03 13:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product_app', '0032_yourmodel'),
    ]

    operations = [
        migrations.DeleteModel(
            name='YourModel',
        ),
    ]
