# Generated by Django 4.2 on 2023-05-03 19:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product_app', '0033_delete_yourmodel'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='item',
            new_name='name',
        ),
    ]
