# Generated by Django 4.2 on 2023-05-04 04:58

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usermodel',
            name='email',
            field=models.EmailField(max_length=50, validators=[django.core.validators.EmailValidator()]),
        ),
    ]
